package com.centroi.alsuper.feature.contacts.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.centroi.alsuper.core.data.EmergencyContactsRepository
import com.centroi.alsuper.core.data.extensions.EncryptionHelper
import com.centroi.alsuper.core.database.tables.EmergencyContact
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject
import kotlin.random.Random

@HiltViewModel
class EmergencyContactsViewModel @Inject constructor(
    private val repository: EmergencyContactsRepository
) : ViewModel() {

    // Fetch and decrypt contacts inside ViewModel
    val emergencyContacts: StateFlow<List<EmergencyContact>> = repository.getEmergencyContacts()
        .map { contacts ->
            contacts.map { contact ->
                contact.copy(
                    phoneNumber = decryptPhoneNumber(contact.phoneNumber) // Decrypt number here
                )
            }
        }
        .stateIn(viewModelScope, SharingStarted.Lazily, emptyList()) // Caches & avoids recomputation

    fun insertContact(name: String, surname: String, phoneNumber: String) {
        val randomColor = generateRandomColor()
        //val randomColor = "#FF0000" // Hardcoded color for now
        val encryptedPhoneNumber = EncryptionHelper.encrypt(phoneNumber)

        val contact = EmergencyContact(
            id = 0, // Auto-generated by Room
            name = name,
            surname = surname,
            phoneNumber = encryptedPhoneNumber,
            color = randomColor,
            isMain = false
        )

        viewModelScope.launch {
            repository.insertContact(contact)
        }
    }

    fun deleteContact(contact: EmergencyContact) {
        viewModelScope.launch {
            repository.deleteContact(contact)
        }
    }

    fun updateContact(contact: EmergencyContact) {
        viewModelScope.launch {
            val encryptedPhoneNumber = EncryptionHelper.encrypt(contact.phoneNumber)

            val updatedContact = contact.copy(
                phoneNumber = encryptedPhoneNumber
            )

            repository.updateContact(updatedContact)
        }
    }

    fun loadContactById(contactId: Int, onResult: (EmergencyContact?) -> Unit) {
        viewModelScope.launch {
            val contact = repository.getContactById(contactId)
            contact?.let {
                val decryptedContact = it.copy(phoneNumber = EncryptionHelper.decrypt(it.phoneNumber))
                onResult(decryptedContact) // Pass the decrypted contact to the UI
            } ?: onResult(null)
        }
    }

    private fun decryptPhoneNumber(encryptedPhone: String): String {
        return try {
            EncryptionHelper.decrypt(encryptedPhone)
        } catch (e: Exception) {
            "Error" // Fallback in case decryption fails
        }
    }

    private fun generateRandomColor(): String {
        val color = java.util.Random().nextInt(0xFFFFFF)
        return "#" + java.lang.String.format("%06X", color)
    }
}